version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "8080:8080"
            - "443:443"
        volumes:
            - ./nginx/conf:/etc/nginx
            - ./nginx/www:/var/www
        depends_on: 
            - api
            - front
    front:
        build:
            context: ./front
        ports: 
            - "9090:9090"
        env_file: ./.env.front-development
        environment: 
            - NODE_ENV=development
        volumes:
            - ./front:/opt/react_app
            - node_modules_front:/opt/react_app/node_modules
        #command: "sh -c 'npm run clean && npm run build && npm run start'"
        command: "npm run dev"
        depends_on: 
            - api
    workers:
        build:
            context: ./workers
        volumes:
            - ./workers:/opt/worker_app
            - node_modules_workers:/opt/worker_app/node_modules
        command: npm run dev
        depends_on: 
            - api
            - db
            - rabbit
    api:
        build: 
            context: ./api
        env_file: ./.env.api-development
        environment: 
            - toto=foo
        volumes: 
            - ./api:/opt/node_app
            - node_modules_api:/opt/node_app/node_modules
        #command: "sh -c 'npm run build && npm run start'"
        command: npm run dev
        depends_on: 
            - db
            - rabbit
    db:
        build: 
            context: ./data
        volumes: 
            - mongodb_data:/data/db
        ports: 
            - "27017:27017"
    rabbit:
        build:
            context: ./rabbitmq
        ports: 
            - "15672:15672"
        hostname: localrabbit
        volumes:
            - rabbit_data:/var/lib/rabbitmq

volumes: 
    node_modules_api:
    node_modules_front:
    node_modules_workers:
    mongodb_data:
    rabbit_data:
