version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf:/etc/nginx
            - ./nginx/www:/var/www
        links: 
            - front
            - api
        depends_on: 
            - api
            - front
    front:
        build:
            context: ./front
        ports: 
            - "9090:9090"
        environment: 
            - NODE_ENV=development
            - API_URI=api
        volumes:
            - ./front:/opt/react_app
            - node_modules_front:/opt/react_app/node_modules
        command: npm run dev-docker
        depends_on: 
            - api
    api:
        build: 
            context: ./api
        environment: 
            - NODE_ENV=development
            - MONGOURI=db
            - FRONTAPPURI=front
        volumes: 
            - ./api:/opt/node_app
            - node_modules_api:/opt/node_app/node_modules
        command: npm run dev
        depends_on: 
            - db
    db:
        build: 
            context: ./data
        volumes: 
            - ./data/db:/data/db"

volumes: 
    node_modules_api:
    node_modules_front: