version: '3'

services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf:/etc/nginx
            - ./nginx/www:/var/www
        links: 
            - front
            - api
        depends_on: 
            - api
            - front
    front:
        build:
            context: ./front
        ports: 
            - "9090:9090"
        env_file: ./.env.front-development
        environment: 
            - NODE_ENV=development
        volumes:
            - ./front:/opt/react_app
            - node_modules_front:/opt/react_app/node_modules
        #command: "sh -c 'npm run clean && npm run build && npm run start'"
        command: "npm run dev"
        depends_on: 
            - api
    api:
        build: 
            context: ./api
        env_file: ./.env.api-development
        environment: 
            - toto=foo
        volumes: 
            - ./api:/opt/node_app
            - node_modules_api:/opt/node_app/node_modules
        #command: "sh -c 'npm run build && npm run start'"
        command: npm run dev
        depends_on: 
            - db
    db:
        build: 
            context: ./data
        volumes: 
            - ./data/db:/data/db"
        ports: 
            - "27017:27017"

volumes: 
    node_modules_api:
    node_modules_front:
